CREATE TABLE usuario (
	id_usuario SERIAL PRIMARY KEY,
	nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
	correo VARCHAR(100) NOT NULL UNIQUE,
	contrasena_hash TEXT NOT NULL,
	id_rol INT NOT NULL,
	estado BOOLEAN NOT NULL DEFAULT TRUE,
	fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_usuario_rol
		FOREIGN KEY (id_rol) REFERENCES ROLES(id_rol)
);